# Use the official Microsoft SQL Server image from Docker Hub
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set environment variables for the SQL Server
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD="Admin@123456789"
ENV MSSQL_PID=Express

# Expose the SQL Server port
EXPOSE 1433

# Run SQL Server
CMD /opt/mssql/bin/sqlservr
