version: '3.8'

services:
  db:
    image: mssql-server-image
    build:
      context: .
      dockerfile: Dockerfile.mssql
    environment:
      SA_PASSWORD: "Admin@123456789"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  hxstudioauthservice:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
